Repository UU-ER/AdOpT-NET0, pull requests merged in 2024-11, with the labels that each got.

#303 Implementing comments from datejada
  joss_submission/paper.bib
  joss_submission/paper.md
Labels: documentation, enhancement

#317 bugfixes and documentation update review
  adopt_net0/components/technologies/genericTechnologies/stor.py
  docs/source/workflow/LoadData.rst
Labels: bug, documentation

#322 Check if solver is available
  adopt_net0/modelhub.py
  requirements.txt
Labels: enhancement

#335 Implemented Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#338 Fixed small documentation issues
  docs/source/ForDevelopers.rst
  docs/source/ModellingWorkflow.rst
  docs/source/workflow/CreateModelTemplates.rst
  docs/source/workflow/DefineModelConfiguration.rst
  docs/source/workflow/LoadData.rst
Labels: documentation
